const fightertunnel = require('fightertunnel');

module.exports = {
    createSSH: fightertunnel.createSSH,
    createTrojan: fightertunnel.createTrojan,
    createVLESS: fightertunnel.createVLESS,
    createShadowsocks: fightertunnel.createShadowsocks,
    createVMess: fightertunnel.createVMess,
    checkSSH: fightertunnel.checkSSH,
    checkVMess: fightertunnel.checkVMess,
    checkTrojan: fightertunnel.checkTrojan,
    checkVLESS: fightertunnel.checkVLESS,
    checkShadowsocks: fightertunnel.checkShadowsocks,
    renewSSH: fightertunnel.renewSSH,
    renewVMess: fightertunnel.renewVMess,
    renewTrojan: fightertunnel.renewTrojan,
    renewVLESS: fightertunnel.renewVLESS,
    renewShadowsocks: fightertunnel.renewShadowsocks,
    trialSSH: fightertunnel.trialSSH,
    trialTrojan: fightertunnel.trialTrojan,
    trialVMess: fightertunnel.trialVMess,
    trialVLess: fightertunnel.trialVLess,
    trialShadowsocks: fightertunnel.trialShadowsocks,
    deleteSSH: fightertunnel.deleteSSH,
    deleteVMess: fightertunnel.deleteVMess,
    deleteTrojan: fightertunnel.deleteTrojan,
    deleteVLESS: fightertunnel.deleteVLESS,
    deleteShadowsocks: fightertunnel.deleteShadowsocks,
};
